### ISSUE TITLE
CockroachDB support: tracking issue

### ISSUE THREAD

**Issue by theduke** [diesel-rs/diesel#1667]
This is a tracking issue for CockroachDB support, listing all issues related to incompatabilities.

* [ ] `information_schema` compatability (#523, #1134)
      This prevents `infer_schema!` and `diesel print-schema` functionality.
* [ ] Do not generate default updated_at migration stored procedure 
      Cockroachdb does not support stored procedures (yet), so the defaul migration generated by `diesel setup`  does not work
* [ ] `diesel database reset` support
     Currently fails with the error ```database postgres does not exist```

**Comment by sgrif** [comment]
I agree with [this comment by a core team member in Gitter](https://gitter.im/diesel-rs/diesel?at=5ae597c35d7286b43a7ccbbf)
